[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.semantic_release]
version_variable = "version.py:__version__"
commit_parser = "semantic_release.commit_parser.angular"
changelog_file = "CHANGELOG.md"
upload_to_pypi = false
upload_to_release = true